# Generated by Django 5.0.7 on 2024-07-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='stug',
            new_name='slug',
        ),
    ]
