# Generated by Django 5.0.7 on 2024-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_stug_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
